---
- name: Create group "bots" for "tor_bot" user account
  group:
    name: bots
    system: true
  become: true

- name: Create "tor_bot" user account under which the ToR bots can execute
  user:
    name: 'tor_bot'
    group: 'bots'
    home: '/var/tor'
    system: true
    create_home: true
    append: true
  become: true
