---
# tasks file for tor_bot

- name: Populate service facts
  service_facts:
- import_tasks: 'python.yml'
- import_tasks: 'redis.yml'
- import_tasks: 'tor_moderator.yml'
- import_tasks: 'tor_archivist.yml'
- import_tasks: 'tor_ocr.yml'
