---

- name: 'Get python executable'
  stat:
    path: /usr/local/bin/python3.8
  register: py_path
- name: 'Get current python version'
  command: /usr/local/bin/python3.8 --version
  when: py_path.stat.exists and py_path.stat.executable
  register: py_version
  changed_when: false

- name: Create temp directory for Python build
  file:
    state: directory
    path: /opt/python-build-dir
    mode: '700'
  when: not py_path.stat.exists or (py_version is defined and '3.8.' not in py_version.stdout)

- name: Download Python 3.8 source
  unarchive:
    dest: /opt/python-build-dir
    remote_src: true
    src: https://www.python.org/ftp/python/3.8.0/Python-3.8.0.tgz
  when: not py_path.stat.exists or (py_version is defined and '3.8.' not in py_version.stdout)

- name: Install system packages to compile python
  package:
    name:
      - gcc
      - openssl-devel
      - bzip2-devel
      - libffi-devel
      - make
    state: present
  become: true
  when: not py_path.stat.exists or (py_version is defined and '3.8.' not in py_version.stdout)

- name: Install system packages to enable python extensions
  package:
    name:
      - readline-devel
      - sqlite-devel
      - gdbm-devel
      - libuuid-devel
      - xz-devel
      - glibc-devel
    state: present
  become: true
  when: not py_path.stat.exists or (py_version is defined and '3.8.' not in py_version.stdout)

- name: Configure Python installer
  command: ./configure --enable-optimizations --enable-profiling --with-lto --with-assertions --with-ensurepip=upgrade
  args:
    chdir: /opt/python-build-dir/Python-3.8.0
  become: true
  when: not py_path.stat.exists or (py_version is defined and '3.8.' not in py_version.stdout)
- name: Compile Python 3.8.0
  command: make
  args:
    chdir: /opt/python-build-dir/Python-3.8.0
  become: true
  when: not py_path.stat.exists or (py_version is defined and '3.8.' not in py_version.stdout)
- name: Install Python 3.8.0 to /usr/local/bin
  command: make install
  args:
    chdir: /opt/python-build-dir/Python-3.8.0
  become: true
  when: not py_path.stat.exists or (py_version is defined and '3.8.' not in py_version.stdout)

- name: Cleanup temp build directory
  file:
    state: absent
    path: /opt/python-build-dir
