---
- name: Get path to RDB backup from which to restory
  stat:
    path: /opt/redis-restore.rdb
  register: redis_restore

- name: Stop redis service
  service:
    name: redis
    state: stopped
  become: true
  when: redis_restore.stat.exists

- name: Restore redis data from backup
  command: mv /opt/redis-restore.rdb /var/lib/redis/dump.rdb
  become: true
  when: redis_restore.stat.exists

- name: Set proper ownership settings for restored RDB
  file:
    path: /var/lib/redis/dump.rdb
    owner: 'redis'
    group: 'redis'
  become: true

- name: 'Start redis service'
  service:
    name: redis
    state: started
  become: true
