---
- import_tasks: 'bot_user.yml'

# Setup a venv
- stat:
    path: /opt/tor_archivist
  register: archivist_venv
- name: 'Create venv for tor_archivist'
  shell: |
    /usr/local/bin/python3.8 -m venv /opt/tor_archivist
  when: archivist_venv.stat.isdir is not defined or not archivist_venv.stat.isdir
  become: true

# Pull down and install the python whl file from the github releases
- name: 'Gather currently installed version of tor_archivist'
  shell: |
    source /opt/tor_archivist/bin/activate
    pip freeze
  register: archivist_pip_freeze
  changed_when: false
- name: 'Download v{{ archivist_version }} of tor_archivist'
  get_url:
    dest: '/tmp/tor_archivist-{{ archivist_version }}-py3-none-any.whl'
    url: 'https://github.com/GrafeasGroup/tor_archivist/releases/download/v{{ archivist_version }}/tor_archivist-{{ archivist_version }}-py3-none-any.whl'
  when: "('tor-archivist=='+archivist_version) not in archivist_pip_freeze.stdout_lines"
- name: 'Install v{{ archivist_version }} of tor_archivist'
  shell: |
    source /opt/tor_archivist/bin/activate
    pip install /tmp/tor_archivist-{{ archivist_version }}-py3-none-any.whl
  become: true
  when: "('tor-archivist=='+archivist_version) not in archivist_pip_freeze.stdout_lines"

# Install credentials files (praw.ini)

- blockinfile:
    path: /opt/tor_archivist/runtime.env
    block: |-
      praw_username={{ archivist_username | quote }}
      praw_password={{ archivist_password | quote }}
      praw_client_id={{ archivist_client_id | quote }}
      praw_client_secret={{ archivist_client_secret | quote }}
      praw_user_agent='python:org.grafeas.tor_archivist:{{ archivist_version }} (by /u/itsthejoker)'
    create: true
    marker: '# {mark} PRAW CREDENTIALS'
- lineinfile:
    path: /opt/tor_archivist/runtime.env
    regex: '^BOT_NAME='
    line: "BOT_NAME='tor_archivist'"
  become: true
- lineinfile:
    path: /opt/tor_archivist/runtime.env
    regex: '^REDIS_CONNECTION_URL='
    line: "REDIS_CONNECTION_URL={{ redis_uri | quote }}"
  become: true
- lineinfile:
    path: /opt/tor_archivist/runtime.env
    regex: '^BUGSNAG_API_KEY='
    line: "BUGSNAG_API_KEY={{ bugsnag_key | quote }}"
  become: true
- lineinfile:
    path: /opt/tor_archivist/runtime.env
    regex: '^SLACK_API_KEY='
    line: "SLACK_API_KEY={{ slack_key | quote }}"
  become: true
- file:
    path: /var/tor/tor_archivist
    state: directory
    owner: 'tor_bot'
    group: 'bots'
  become: true
- lineinfile:
    path: /opt/tor_archivist/runtime.env
    regex: '^HEARTBEAT_FILE='
    line: "HEARTBEAT_FILE='/var/tor/tor_archivist/heartbeat.port'"
  become: true

# Install systemd unit
- template:
    src: 'systemd-service.j2'
    dest: '/etc/systemd/system/tor_archivist.service'
  become: true
  vars:
    description: 'The content curation bot for /r/TranscribersOfReddit'
    github_repo_url: 'https://github.com/GrafeasGroup/tor_archivist'
    bot: 'tor_archivist'
    bin: 'tor-archivist'
- systemd:
    daemon_reload: true
    enabled: true
    name: 'tor_archivist.service'
