---

- name: Get venv path
  stat:
    path: /opt/tor_tools
  register: tools_venv
- name: Create venv for tor_tools
  command: /usr/local/bin/python3.8 -m venv /opt/tor_tools
  when: tools_venv.stat.isdir is not defined or not tools_venv.stat.isdir
  become: true

- name: Gather currently installed version of tor_tools
  shell: |
    source /opt/tor_tools/bin/activate
    pip freeze
  register: tools_pip_freeze
  changed_when: false
- name: 'Download v{{ tools_version }} of tor_tools'
  get_url:
    dest: '/tmp/tor_tools-{{ tools_version }}-py3-none-any.whl'
    url: 'https://github.com/GrafeasGroup/tor-tools/releases/download/v{{ tools_version }}/tor_tools-{{ tools_version }}-py3-none-any.whl'
  when: "('tor-tools=='+tools_version) not in tools_pip_freeze.stdout_lines"
- name: 'Install v{{ tools_version }} of tor_tools'
  shell: |
    source /opt/tor_tools/bin/activate
    pip install /tmp/tor_tools-{{ tools_version }}-py3-none-any.whl
  become: true
  when: "('tor-tools=='+tools_version) not in tools_pip_freeze.stdout_lines"
  notify:
    - restart shadowban checker

- name: Add runtime environment for tor_tools.service
  blockinfile:
    path: /opt/tor_tools/runtime.env
    block: |
      BOTS_LIST='transcribersofreddit,tor_archivist,transcribot'
      SLACK_API_KEY={{ slack_key | quote }}
    create: true
    marker: '# {mark} TOR BOT INFO'
    mode: '0600'
  become: true
  notify:
    - restart shadowban checker

- name: Create 'tor_tools.service' systemd unit
  template:
    src: systemd-service-other.j2
    dest: /etc/systemd/system/tor_tools.service
    mode: '0644'
  become: true
  vars:
    venv: tor_tools
    description: 'Monitors if any of the TranscribersOfReddit bots get shadowbanned by the admins'
    github_repo_url: https://github.com/GrafeasGroup/tor-tools
    bin: tor-shadowbanned
  notify:
    - restart shadowban checker
- name: Set 'tor_tools.service' to start at boot
  systemd:
    daemon_reload: true
    enabled: true
    name: tor_tools.service
