---
- import_tasks: 'bot_user.yml'

- name: Get venv path
  stat:
    path: /opt/tor_ocr
  register: ocr_venv
- name: Create venv for tor_ocr
  command: /usr/local/bin/python3.8 -m venv /opt/tor_ocr
  when: ocr_venv.stat.isdir is not defined or not ocr_venv.stat.isdir
  become: true

- name: Gather currently installed version of tor_ocr
  shell: |
    source /opt/tor_ocr/bin/activate
    pip freeze
  register: ocr_pip_freeze
  changed_when: false
- name: 'Download v{{ ocr_version }} of tor_ocr'
  get_url:
    dest: '/tmp/tor_ocr-{{ ocr_version }}-py3-none-any.whl'
    url: 'https://github.com/GrafeasGroup/tor_ocr/releases/download/v{{ ocr_version }}/tor_ocr-{{ ocr_version }}-py3-none-any.whl'
  when: "('tor-ocr=='+ocr_version) not in ocr_pip_freeze.stdout_lines"
- name: 'Install v{{ ocr_version }} of tor_ocr'
  shell: |
    source /opt/tor_ocr/bin/activate
    pip install /tmp/tor_ocr-{{ ocr_version }}-py3-none-any.whl
  become: true
  when: "('tor-ocr=='+ocr_version) not in ocr_pip_freeze.stdout_lines"
  notify:
    - restart ocr bot

- name: Create tor_ocr runtime directory
  file:
    path: /var/tor/tor_ocr
    state: directory
    owner: tor_bot
    group: bots
  become: true
- name: Add reddit creds to runtime environment for tor_ocr.service
  blockinfile:
    path: /opt/tor_ocr/runtime.env
    block: |-
      praw_username={{ ocr_username | quote }}
      praw_password={{ ocr_password | quote }}
      praw_client_id={{ ocr_client_id | quote }}
      praw_client_secret={{ ocr_client_secret | quote }}
      praw_user_agent='python:org.grafeas.tor_ocr:{{ ocr_version }} (by /u/itsthejoker)'
    create: true
    marker: '# {mark} PRAW CREDENTIALS'
  notify:
    - restart ocr bot
- name: Add bot metadata to runtime environment for tor_ocr.service
  blockinfile:
    path: /opt/tor_ocr/runtime.env
    block: |
      BOT_NAME='tor_ocr'
      REDIS_CONNECTION_URL={{ redis_uri | quote }}
      HEARTBEAT_FILE='/var/tor/tor_ocr/heartbeat.port'
      BUGSNAG_API_KEY={{ bugsnag_key | quote }}
      SLACK_API_KEY={{ slack_key | quote }}
    create: true
    marker: '# {mark} TOR BOT INFO'
  become: true
  notify:
    - restart ocr bot

- name: Create 'tor_ocr.service' systemd unit
  template:
    src: systemd-service.j2
    dest: /etc/systemd/system/tor_ocr.service
  become: true
  vars:
    description: The content curation bot for /r/TranscribersOfReddit
    github_repo_url: https://github.com/GrafeasGroup/tor_ocr
    bot: tor_ocr
    bin: tor-apprentice
  notify:
    - restart ocr bot
- name: Set 'tor_ocr.service' to start at boot
  systemd:
    daemon_reload: true
    enabled: true
    name: tor_ocr.service
