---
- import_tasks: 'bot_user.yml'

- name: Get venv path
  stat:
    path: /opt/tor_moderator
  register: moderator_venv
- name: Create venv for tor_moderator
  command: /usr/local/bin/python3.8 -m venv /opt/tor_moderator
  when: moderator_venv.stat.isdir is not defined or not moderator_venv.stat.isdir
  become: true

- name: Gather currently installed version of tor_moderator
  shell: |
    source /opt/tor_moderator/bin/activate
    pip freeze
  register: moderator_pip_freeze
  changed_when: false
- name: 'Download v{{ moderator_version }} of tor_moderator'
  get_url:
    dest: '/tmp/tor-{{ moderator_version }}-py3-none-any.whl'
    url: 'https://github.com/GrafeasGroup/tor/releases/download/v{{ moderator_version }}/tor-{{ moderator_version }}-py3-none-any.whl'
  when: "('tor=='+moderator_version) not in moderator_pip_freeze.stdout_lines"
- name: 'Install v{{ moderator_version }} of tor_moderator'
  shell: |
    source /opt/tor_moderator/bin/activate
    pip install /tmp/tor-{{ moderator_version }}-py3-none-any.whl
  become: true
  when: "('tor=='+moderator_version) not in moderator_pip_freeze.stdout_lines"
  notify:
    - restart moderator bot

- name: Create tor_moderator runtime directory
  file:
    path: /var/tor/tor_moderator
    state: directory
    owner: 'tor_bot'
    group: 'bots'
    mode: '0700'
  become: true
- name: Add reddit creds to runtime environment for tor_moderator.service
  blockinfile:
    path: /opt/tor_moderator/runtime.env
    block: |-
      praw_username={{ moderator_username | quote }}
      praw_password={{ moderator_password | quote }}
      praw_client_id={{ moderator_client_id | quote }}
      praw_client_secret={{ moderator_client_secret | quote }}
      praw_user_agent='python:org.grafeas.tor_moderator:{{ moderator_version }} (by /u/itsthejoker)'
    create: true
    marker: '# {mark} PRAW CREDENTIALS'
    mode: '0600'
  notify:
    - restart moderator bot
- name: Add bot metadata to runtime environment for tor_moderator.service
  blockinfile:
    path: /opt/tor_moderator/runtime.env
    block: |
      BOT_NAME='tor'
      REDIS_CONNECTION_URL={{ redis_uri | quote }}
      HEARTBEAT_FILE='/var/tor/tor_moderator/heartbeat.port'
      BUGSNAG_API_KEY={{ bugsnag_key | quote }}
      SLACK_API_KEY={{ slack_key | quote }}
    create: true
    marker: '# {mark} TOR BOT INFO'
    mode: '0600'
  become: true
  notify:
    - restart moderator bot

- name: Create 'tor_moderator.service' systemd unit
  template:
    src: systemd-service.j2
    dest: /etc/systemd/system/tor_moderator.service
    mode: '0644'
  become: true
  vars:
    description: The claim, done, and scoring bot for /r/TranscribersOfReddit
    github_repo_url: https://github.com/GrafeasGroup/tor
    bot: tor_moderator
    bin: tor-moderator
  notify:
    - restart moderator bot
- name: Set 'tor_moderator.service' to start at boot
  systemd:
    daemon_reload: true
    enabled: true
    name: tor_moderator.service
