---

- hosts: localhost
  gather_facts: false
  vars_prompt:
    - name: password
      prompt: 'What is the password?'
      private: true
  tasks:
    - debug:
        msg: "{{ password | password_hash('sha512', salt) }}"
