---
- name: Install/Upgrade Blossom
  hosts: web
  tasks:
    # TODO: fill this in with stuff to provision Blossom, et al.
    - name: Confirm connectivity
      ping:

- name: Install/Upgrade bots
  hosts: bots
  tasks:
    - import_role:
        name: reddit_bot
      vars:
        bot_name: tor-moderator
        bot_repo: tor
        bot_cmd: tor-moderator
        bot: '{{ reddit_info.tor_moderator | default(omit) }}'
    - import_role:
        name: reddit_bot
      vars:
        bot_name: tor-archivist
        bot_repo: tor_archivist
        bot_cmd: tor-archivist
        bot: '{{ reddit_info.tor_archivist | default(omit) }}'
    - import_role:
        name: reddit_bot
      vars:
        bot_name: tor-ocr
        bot_repo: tor_ocr
        bot_cmd: tor-apprentice
        bot: '{{ reddit_info.tor_ocr | default(omit) }}'

- name: Start bots
  hosts: bots
  tasks:
    - name: Start bots
      systemd:
        name: '{{ item }}'
        state: started
      become: true
      loop:
        - tor-moderator
        - tor-archivist
        - tor-ocr

# vim: ft=yaml.ansible
