---

- yum:
    name: '*'
    state: latest

- file:
    state: directory
    path: /var/log/journal
  become: true
  notify: restart journald

- group: 
    name: sudo
    state: present
  become: true

- lineinfile:
    regexp: '^%sudo '
    line: '%sudo ALL=(ALL) ALL'
    path: /etc/sudoers.d/sudoers
    validate: '/usr/sbin/visudo -cf %s'
    create: true
    owner: root
    group: root
    mode: 0440
  become: true

- include_tasks: 'create_user.yml'
  vars:
    username: '{{ item.username }}'
    password_hash: '{{ item.password_hash }}'
    public_key: '{{ item.public_key }}'
  loop: '{{ admin_info }}'
