---
- hosts: bots
  tasks:
    - import_role:
        name: 'tor_bot'
        tasks_from: 'tor_moderator.yml'
    - import_role:
        name: 'tor_bot'
        tasks_from: 'tor_archivist.yml'
    - import_role:
        name: 'tor_bot'
        tasks_from: 'tor_ocr.yml'
