name: Ansible Playbook

on:
  push:
    branches:
      - 'master'

jobs:
  apply:

    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v1
      with:
        ssh-key: ${{ secrets.SSH_KEY_ANSIBLE_INVENTORY }}
        submodule: 'recursive'
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
        architecture: 'x64'
    - name: Setup Ansible
      run: |
        python3 -m pip install --upgrade pip
        python3 -m venv venv
        source ./venv/bin/activate
        hash -r

        printf '%s\n' "$SSH_KEY" > ./private_key
        chmod 600 ./private_key

        python3 -m pip install -r requirements.txt
        hash -r

        ansible-galaxy install -r ./requirements.yml
      env:
        SSH_KEY: ${{ secrets.SSH_KEY_REMOTE_USER }}
