name: Ansible Playbook

on:
  push:
    branches:
      - 'master'

jobs:
  apply:

    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v1
    - run: rm -rf ./inventory
    - uses: actions/checkout@v1
      with:
        repository: 'git@github.com:GrafeasGroup/ansible-secrets.git'
        ssh-key: ${{ secrets.GITHUB_SSH_KEY_ANSIBLE_INVENTORY }}
        path: 'inventory'
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
        architecture: 'x64'
    - name: Setup Ansible
      run: |
        python3 -m pip install --upgrade pip
        python3 -m venv venv
        source ./venv/bin/activate
        hash -r

        printf '%s\n' "${{ secrets.SSH_KEY_REMOTE_USER }}" > ./private_key
        chmod 600 ./private_key

        python3 -m pip install -r requirements.txt
        hash -r

        ansible-galaxy collection install -r ./requirements.yml
        ansible-galaxy role install -r ./requirements.yml
