name: Validate

on:
  pull_request:
    branches:
      - 'master'

jobs:
  lint:
    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v1
      with:
        ssh-key: ${{ secrets.SSH_KEY_ANSIBLE_INVENTORY }}
        submodule: 'recursive'
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
        architecture: 'x64'
    - name: Setup Ansible
      run: |
        python3 -m pip install --upgrade pip
        python3 -m venv venv
        source ./venv/bin/activate
        hash -r

        python3 -m pip install --upgrade setuptools
        python3 -m pip install -r dev-requirements.txt

    - name: Ansible Lint
      id: lint
      run: |
        source ./venv/bin/activate
        hash -r

        ansible-lint $(find . -maxdepth 1 -mindepth 1 \( -name '*.yml' -or -name '*.yaml' \) -print)

  inventory:
    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v1
      with:
        ssh-key: ${{ secrets.SSH_KEY_ANSIBLE_INVENTORY }}
        submodule: 'recursive'
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
        architecture: 'x64'
    - name: Setup Ansible
      run: |
        python3 -m pip install --upgrade pip
        python3 -m venv venv
        source ./venv/bin/activate
        hash -r

        printf '%s\n' "$SSH_KEY" > ./private_key
        chmod 600 ./private_key

        python3 -m pip install -r requirements.txt
        hash -r

        ansible-galaxy install -r ./requirements.yml
      env:
        SSH_KEY: ${{ secrets.SSH_KEY_REMOTE_USER }}

    - name: Ansible Inventory
      id: inventory
      run: |
        source ./venv/bin/activate
        hash -r

        ansible -m ping all
      env:
        ANSIBLE_PRIVATE_KEY_FILE: './private_key'
        ANSIBLE_REMOTE_USER: ${{ secrets.REMOTE_USER }}
