---
- service_facts:  # noqa 502

- name: Get latest packaged release
  community.general.github_release:
    user: GrafeasGroup
    repo: '{{ bot_repo | mandatory }}'
    action: latest_release
    token: '{{ github_token | default(omit) }}'
  register: github

- name: Download wheel package
  get_url:
    url: ''
    dest: /tmp/
    owner: '{{ bot_name }}'
    group: '{{ bot_name }}'
  register: whl
  # notify:
  #   - compile requirements.txt
  become: true
  become_user: '{{ bot_name }}'

- name: Read name from wheel metadata
  shell:
    # This unzips the wheel file (it's just a specifically structured ZIP file) and
    # parses the METADATA file to reformat it into something `pip-compile` can parse
    cmd: |
      unzip -a -p {{ whl.dest | quote }} *.dist-info/METADATA | awk '/^Name: / { print $2 }'
  # This is a read operation, which doesn't even write to the filesystem
  changed_when: false
  register: whl_name

- name: Read requirements from wheel metadata
  shell:
    # This unzips the wheel file (it's just a specifically structured ZIP file) and
    # parses the METADATA file to reformat it into something `pip-compile` can parse
    cmd: |
      unzip -a -p {{ whl.dest | quote }} *.dist-info/METADATA | awk '/^Requires-Dist: / { gsub("[)(]","",$3); print $2 $3 }'
  # This is a read operation, which doesn't even write to the filesystem
  changed_when: false
  register: requirements_in

- name: Write requirements.in
  file:
    content: |
      {{ requirements_in.stdout }}
      {{ whl.dest }}
    path: '{{ venv_path | quote }}/requirements.in'
    owner: '{{ bot_name }}'
    group: '{{ bot_name }}'
    mode: '644'
  notify:
    - compile requirements.txt
  become: true
  become_user: '{{ bot_user }}'

- meta: flush_handlers

- name: Conservatively install package and dependencies
  shell:
    # The `yes | pip-sync --ask --quiet` gets us to output to stdout
    # if there's a change, but not if it wouldn't install anything.
    # This allows us to translate to idempotence checks Ansible looks
    # for.
    #
    # This does not upgrade anything unless it is explicitly required,
    # and will uninstall if removed as dependencies.
    cmd: |
      source {{ venv_path | quote }}/bin/activate &>/dev/null

      yes | pip-sync --ask --quiet {{ venv_path | quote }}/requirements.txt
  become: true
  become_user: '{{ bot_user }}'
  register: whl_install
  changed_when: whl_install.stdout

- name: 'Directory for app-specific env vars'
  file:
    path: /etc/sysconfig
    state: directory
    owner: root
    group: root
    mode: '755'
  become: true

- name: Service secrets (systemd)
  template:
    dest: '/etc/sysconfig/{{ bot_name }}'
    src: env.sh.j2
    owner: root
    group: root
    mode: '600'
  become: true


- name: Service unit (systemd)
  template:
    dest: '/etc/systemd/system/{{ bot_name }}.service'
    src: bot.service.j2
    owner: root
    group: root
    mode: '644'
  notify: smart restart service
  become: true

# vim: ft=yaml.ansible
